
const INITIAL_GIFTS = [
  {
    id: 'gift-1',
    title: 'Jantar Harmonizado na Asttore Forneria',
    category: 'Experiências',
    price: 380,
    description: 'Um brinde especial aos 10 anos de caminhada com vinho tinto de guarda e culinária artesanal.',
  },
  {
    id: 'gift-2',
    title: 'Cota para o Projeto do Nosso Terreno',
    category: 'Novo Lar',
    price: 650,
    description: 'Pedra fundamental para erguermos as paredes da casa onde nossos sonhos terão raízes.',
  },
  {
    id: 'gift-3',
    title: 'Banquete Real para os 6 Pets da Família',
    category: 'Família & Pets',
    price: 190,
    description: 'Mimos especiais para 1 cachorro, 1 gato, 2 peixes e 2 periquitos que alegram nossos dias.',
  },
  {
    id: 'gift-4',
    title: 'Café da Manhã Imperial de Lua de Mel',
    category: 'Lua de Mel',
    price: 240,
    description: 'A primeira manhã pós-casamento celebrada com calma, cafés especiais e vista para o mar.',
  },
  {
    id: 'gift-5',
    title: 'Amortização Mágica dos 2 Empréstimos',
    category: 'Novo Lar',
    price: 450,
    description: 'Um feitiço financeiro poderoso para deixar nossa jornada ainda mais leve e próspera.',
  },
  {
    id: 'gift-6',
    title: 'Conjunto de Cristais & Decanter Clássico',
    category: 'Novo Lar',
    price: 320,
    description: 'Taças de cristal lapidado para recebermos nossos amigos e familiares em datas memoráveis.',
  },
  {
    id: 'gift-7',
    title: 'Passeio em Família com Nosso Filho',
    category: 'Família & Pets',
    price: 290,
    description: 'Um dia de aventura e memórias inesquecíveis para celebrarmos a união com nosso pequeno de 7 anos.',
  },
  {
    id: 'gift-8',
    title: 'Estadia Romântica de Lua de Mel',
    category: 'Lua de Mel',
    price: 890,
    description: 'Noites estreladas de descanso após uma década construindo nossa história lado a lado.',
  },
  {
    id: 'gift-9',
    title: 'Biblioteca Particular do Casal',
    category: 'Experiências',
    price: 220,
    description: 'Edições encadernadas em capa dura para nossa estante e leituras compartilhadas.',
  },
];

const INITIAL_MEMORIES = [
  {
    id: 'mem-1',
    senderName: 'Madrinha Helena & Tio Roberto',
    whatsapp: '(85) 99912-4410',
    giftTitle: 'Cota para o Projeto do Nosso Terreno',
    giftAmount: 650,
    message:
      'Lembro de vocês dois ainda crianças no Jardim de Infância da Escola Centro Acadêmico. Ver o amor de vocês florescer com um filho lindo e uma família tão cheia de vida é emocionante. Sempre!',
    createdAt: '14 Fev 2027',
    isVisible: true,
  },
  {
    id: 'mem-2',
    senderName: 'Lucas & Beatriz Albuquerque',
    whatsapp: '(85) 98845-1920',
    giftTitle: 'Jantar Harmonizado na Asttore Forneria',
    giftAmount: 380,
    message:
      'Que o dia 18 de março de 2027 seja apenas o capítulo mais luminoso de uma obra que vocês escrevem há dez anos. Saúde para vocês, para o pequeno e até para os periquitos e peixes!',
    createdAt: '18 Fev 2027',
    isVisible: true,
  },
  {
    id: 'mem-3',
    senderName: 'Família Landim (Cláudio & Suzana)',
    whatsapp: '(85) 99711-0833',
    giftTitle: 'Estadia Romântica de Lua de Mel',
    giftAmount: 890,
    message:
      'Depois de todo esse tempo? Sempre! Orgulho imenso da família que vocês construíram com tanta coragem, humor e cumplicidade.',
    createdAt: '21 Fev 2027',
    isVisible: true,
  },
  {
    id: 'mem-4',
    senderName: 'Gabriel & Camila Montenegro',
    whatsapp: '(85) 99630-5501',
    giftTitle: 'Amortização Mágica dos 2 Empréstimos',
    giftAmount: 450,
    message:
      'A história de vocês prova que a magia mais poderosa é aquela construída no dia a dia: nos boletos vencidos juntos, no terreno sonhado e nas risadas em casa.',
    createdAt: '25 Fev 2027',
    isVisible: true,
  },
  {
    id: 'mem-5',
    senderName: 'Dra. Patrícia Fontenelle',
    whatsapp: '(85) 99104-7782',
    giftTitle: 'Conjunto de Cristais & Decanter Clássico',
    giftAmount: 320,
    message:
      'Suzy e Junior, que a casa de vocês continue sendo esse porto seguro de afeto e alegria. Estaremos na Paróquia N. Sra. da Glória aplaudindo de pé!',
    createdAt: '01 Mar 2027',
    isVisible: true,
  },
  {
    id: 'mem-6',
    senderName: 'Rafael, Mariana & Theo',
    whatsapp: '(85) 98722-3319',
    giftTitle: 'Banquete Real para os 6 Pets da Família',
    giftAmount: 190,
    message:
      'Nosso presente vai direto para a guarda real de quatro patas, nadadeiras e penas! Que venha o grande dia em Fortaleza!',
    createdAt: '04 Mar 2027',
    isVisible: true,
  },
];

const INITIAL_GUESTS = [
  {
    id: 'rsvp-1',
    name: 'Cláudio & Suzana Landim',
    whatsapp: '(85) 99711-0833',
    companions: 2,
    confirmedAt: '10 Fev 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-2',
    name: 'Madrinha Helena & Tio Roberto',
    whatsapp: '(85) 99912-4410',
    companions: 1,
    confirmedAt: '12 Fev 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-3',
    name: 'Lucas & Beatriz Albuquerque',
    whatsapp: '(85) 98845-1920',
    companions: 1,
    confirmedAt: '15 Fev 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-4',
    name: 'Gabriel & Camila Montenegro',
    whatsapp: '(85) 99630-5501',
    companions: 2,
    confirmedAt: '19 Fev 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-5',
    name: 'Dra. Patrícia Fontenelle',
    whatsapp: '(85) 99104-7782',
    companions: 0,
    confirmedAt: '22 Fev 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-6',
    name: 'Rafael, Mariana & Theo',
    whatsapp: '(85) 98722-3319',
    companions: 2,
    confirmedAt: '26 Fev 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-7',
    name: 'Arthur Landim & Carolina',
    whatsapp: '(85) 99418-6021',
    companions: 1,
    confirmedAt: '28 Fev 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-8',
    name: 'Profª. Clara Vasconcelos (Centro Acadêmico)',
    whatsapp: '(85) 98610-9044',
    companions: 1,
    confirmedAt: '02 Mar 2027',
    isVisible: true,
  },
  {
    id: 'rsvp-9',
    name: 'Henrique & Sofia Bezerra',
    whatsapp: '(85) 99205-1188',
    companions: 3,
    confirmedAt: '05 Mar 2027',
    isVisible: true,
  },
];

const INITIAL_SUPPLIERS = [
  {
    id: 'sup-1',
    name: 'Asttore Forneria',
    role: 'Recepção, Gastronomia & Carta de Vinhos',
    contact: '(85) 3267-4410',
    cost: 18500,
    paidAmount: 14000,
    status: 'Contratado',
    isVisible: true,
  },
  {
    id: 'sup-2',
    name: 'Paróquia Nossa Senhora da Glória',
    role: 'Cerimônia Religiosa (10h) & Coral Litúrgico',
    contact: '(85) 3271-1905',
    cost: 4200,
    paidAmount: 4200,
    status: 'Quitado',
    isVisible: true,
  },
  {
    id: 'sup-3',
    name: 'Atelier Lumière & Velas',
    role: 'Decoração Dark Academia & Arranjos Clássicos',
    contact: '(85) 99811-2300',
    cost: 9800,
    paidAmount: 6500,
    status: 'Contratado',
    isVisible: true,
  },
  {
    id: 'sup-4',
    name: 'Quarteto de Cordas Opus Fortaleza',
    role: 'Trilha Instrumental da Cerimônia e Recepção',
    contact: '(85) 99140-8870',
    cost: 5400,
    paidAmount: 2700,
    status: 'Contratado',
    isVisible: true,
  },
];
export { INITIAL_GIFTS, INITIAL_MEMORIES, INITIAL_GUESTS, INITIAL_SUPPLIERS };
